name: emoncms
description: The webapp for energy monitoring and more
version: alpine3.16.3
image: alexjunk/emoncms
webui: http://[HOST]:[PORT:8002]
slug: emoncms
url: https://github.com/Open-Building-Management/emoncms/issues
init: false
arch:
  - armv7
  - aarch64
  - amd64
services:
  - emoncms:provide
ports:
  80/tcp: 8002
  1883/tcp: 9883
options:
  TZ: Europe/Paris
  MQTT_HOST: localhost
  MQTT_USER: emonpi
  MQTT_PASSWORD: emonpimqtt2016
  MQTT_LOG_LEVEL: error
  EMONCMS_LOG_LEVEL: 2
  LOW_WRITE_MODE: true
schema:
  TZ: str
  MQTT_HOST: str
  MQTT_USER: str
  MQTT_PASSWORD: str
  MQTT_LOG_LEVEL: list(error|information|notice|all)
  EMONCMS_LOG_LEVEL: list(1|2|3)
  LOW_WRITE_MODE: bool
