name: emoncms
description: The webapp for energy monitoring and more
version: alpine3.16
image: alexjunk/emoncms
webui: http://[HOST]:[PORT:8002]
slug: emoncms
url: https://github.com/Open-Building-Management/emoncms/issues
init: false
arch:
  - armv7
  - aarch64
  - amd64
ports:
  80/tcp: 8002
  1883/tcp: 9883
options:
  MQTT_USER: emonpi
  MQTT_PASSWORD: emonpimqtt2016
schema:
  MQTT_USER: str
  MQTT_PASSWORD: str
