name: emoncms
description: The webapp for energy monitoring and more
version: alpine3.19_emoncms11.4.11_1
image: alexjunk/emoncms
webui: http://[HOST]:[PORT:8002]
slug: emoncms
url: https://github.com/Open-Building-Management/emoncms/issues
init: false
arch:
  - armv7
  - aarch64
  - amd64
map:
  - all_addon_configs
  - addon_config:rw
  - ssl
ports:
  443/tcp: 7443
  80/tcp: 8002
  1883/tcp: 9883
options:
  TZ: Europe/Paris
  MQTT_HOST: localhost
  MQTT_USER: emonpi
  MQTT_PASSWORD: emonpimqtt2016
  MQTT_LOG_LEVEL: error
  EMONCMS_LOG_LEVEL: 2
  LOW_WRITE_MODE: true
  CUSTOM_APACHE_CONF: false
  CRT_FILE: /etc/ssl/apache2/server.pem
  KEY_FILE: /etc/ssl/apache2/server.key
  CNAME: localhost
schema:
  TZ: str
  MQTT_HOST: str
  MQTT_USER: str
  MQTT_PASSWORD: str
  MQTT_LOG_LEVEL: list(error|information|notice|all)
  EMONCMS_LOG_LEVEL: list(1|2|3)
  LOW_WRITE_MODE: bool
  CUSTOM_APACHE_CONF: bool
  CRT_FILE: str
  KEY_FILE: str
  CNAME: str
