name: emoncms docker images to docker hub -  mention of emoncms version

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      emoncms_src: emoncms/emoncms
      branch: master
    strategy:
      matrix:
        include:
          - alpine_version: '3.19.1'
            php_version: 82
            use_redispy_apk: 1
          - alpine_version: '3.20'
            php_version: 83
            use_redispy_apk: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: emoncms_version
        name: get emoncms version
        run: |
          wget https://raw.githubusercontent.com/${{ env.emoncms_src }}/${{ env.branch }}/version.json
          version=$(cat version.json | jq --raw-output '.version')
          echo $version
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            "EMONCMS_SRC=https://github.com/${{ env.emoncms_src }}"
            "BRANCH=${{ env.branch }}"
            "BUILD_FROM=alpine:${{ matrix.alpine_version }}"
            "PHP_VER=${{ matrix.php_version }}"
            "PHP_CONF=/etc/php${{ matrix.php_version }}/conf.d"
            "USE_REDISPY_APK=${{ matrix.use_redispy_apk }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/emoncms:alpine${{ matrix.alpine_version }}_emoncms${{ steps.emoncms_version.outputs.version }}
